# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto2.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cproto2.proto\"\x8f\x02\n\x08\x43urrData\x12\x0e\n\x06\x43\x41R_ID\x18\x01 \x01(\t\x12\x0b\n\x03RPM\x18\x02 \x01(\x01\x12\r\n\x05SPEED\x18\x03 \x01(\x02\x12\x10\n\x08RUN_TIME\x18\x04 \x01(\x02\x12\x1e\n\x16\x43ONTROL_MODULE_VOLTAGE\x18\x05 \x01(\x02\x12\x18\n\x10\x41MBIANT_AIR_TEMP\x18\x06 \x01(\x02\x12\x11\n\tFUEL_TYPE\x18\x07 \x01(\t\x12\x10\n\x08OIL_TEMP\x18\x08 \x01(\x02\x12\x18\n\x10\x46UEL_CONSUMPTION\x18\t \x01(\x02\x12!\n\x19TOTAL_DISTANCE_SINCE_JOIN\x18\n \x01(\x02\x12\x0b\n\x03\x44TC\x18\x0b \x01(\t\x12\x1c\n\x14\x41VG_FUEL_CONSUMPTION\x18\x0c \x01(\x02\x62\x06proto3')
)




_CURRDATA = _descriptor.Descriptor(
  name='CurrData',
  full_name='CurrData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CAR_ID', full_name='CurrData.CAR_ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RPM', full_name='CurrData.RPM', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SPEED', full_name='CurrData.SPEED', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RUN_TIME', full_name='CurrData.RUN_TIME', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CONTROL_MODULE_VOLTAGE', full_name='CurrData.CONTROL_MODULE_VOLTAGE', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AMBIANT_AIR_TEMP', full_name='CurrData.AMBIANT_AIR_TEMP', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FUEL_TYPE', full_name='CurrData.FUEL_TYPE', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OIL_TEMP', full_name='CurrData.OIL_TEMP', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FUEL_CONSUMPTION', full_name='CurrData.FUEL_CONSUMPTION', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TOTAL_DISTANCE_SINCE_JOIN', full_name='CurrData.TOTAL_DISTANCE_SINCE_JOIN', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DTC', full_name='CurrData.DTC', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AVG_FUEL_CONSUMPTION', full_name='CurrData.AVG_FUEL_CONSUMPTION', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=288,
)

DESCRIPTOR.message_types_by_name['CurrData'] = _CURRDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurrData = _reflection.GeneratedProtocolMessageType('CurrData', (_message.Message,), dict(
  DESCRIPTOR = _CURRDATA,
  __module__ = 'proto2_pb2'
  # @@protoc_insertion_point(class_scope:CurrData)
  ))
_sym_db.RegisterMessage(CurrData)


# @@protoc_insertion_point(module_scope)
